name: my workflow # WorkfLow 이름
on:
  push: # main branch에서 push 이벤트가 일어났을 때만 실행
    branches:
      - main

jobs: # Job 설정
  build: # Job ID
    name: hello github action # Job 이름
    runs-on: ubuntu-latest # Job 가상환경 인스턴스
    env:
      working-directory: ./blog-frontend
    steps:
      - name: checkout source code # 레포지토리 체크아웃
        uses: actions/checkout@v3

      - name: Set up Node v
        run: node -v

      - name: Install Dependencies # 의존 파일 설치
        run: npm install # Run을 통한 스크립트 실행: HelLo 출력
        working-directory: ${{ env.working-directory }} # 특정 디렉터리에서 실행

      - name: Build # React Build
        run: npm run build
        working-directory: ${{ env.working-directory }}
